load benchmarks/onethirdrule/onethirdrule-hs.maude
load search.maude
load qtable.maude

mod TEST-BFS is
  pr SEARCH .
  pr ONETHIRDRULE-ANALYSIS .
  pr BFS-SCORE .
  op M : -> Module .
  eq M = upModule('ONETHIRDRULE-ANALYSIS,true) .
endm


mod TEST-DFS is
  pr SEARCH .
  pr ONETHIRDRULE-ANALYSIS .
  pr DFS-SCORE .
  op M : -> Module .
  eq M = upModule('ONETHIRDRULE-ANALYSIS,true) .
endm


mod TEST-QHS is
  pr SEARCH .
  pr ONETHIRDRULE-ANALYSIS .
  pr QHS-SCORE .
  op M : -> Module .
  eq M = upModule('ONETHIRDRULE-ANALYSIS,true) .
endm


mod TEST-CONST is
  pr SEARCH .
  pr ONETHIRDRULE-ANALYSIS .
  pr CONST-SCORE .
  op M : -> Module .
  eq M = upModule('ONETHIRDRULE-ANALYSIS,true) .
endm

---red in TEST-QHS : search(M, upTerm(init4), disagree) .
---red in TEST-BFS : search(M, upTerm(init4), disagree) .
---red in TEST-DFS : search(M, upTerm(init4), disagree) .
---red in TEST-CONST : search(M, upTerm(init4), disagree) .
