load ../benchmarks/dining-philosophers/dining-philosophers-analysis .
--- load ../benchmarks/dining-philosophers/dining-philosophers-focus-analysis .

mod DINING-PHILOSOPHERS-INIT3 is
  pr MODEL .
  op goal : -> Prop .
  eq goal = deadlock .
  
  op init : -> Conf .
  eq init = p(0, think) || p(1, think) || p(2, think) || c(0) || c(1) || c(2) .
  eq #N = 3 .
endm

--- search [1] init =>* C:Conf such that C:Conf |= deadlock = true .
