--- load ../benchmarks/filter-analysis .
load ../benchmarks/filter-focus-analysis .

mod FILTER-INIT5 is
  pr MODEL .
  op goal : -> Prop .
  eq goal = twoCrits .
  
  op init : -> Conf .
  eq init = vict(1,0) vict(2,0) vict(3,0) vict(4,0) ; proc(1, 0, on) proc(2, 0, on) proc(3, 0, on) proc(4, 0, on) proc(5, 0, on) . --- error
  eq @NL = 4 .
endm

--- search [1] init =>* VS:VictSet ; proc(I:Nat, L:Nat, crit) proc(J:Nat, L:Nat, crit) PS:ProcSet such that I:Nat =/= J:Nat .
